language: android
android:
  components:
    - tools
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
jdk:
  - oraclejdk8
branches:
  except:
    - gh-pages
git:
  depth: 50
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee"
    > "$ANDROID_HOME/licenses/android-sdk-license"
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - ".+"
script: if [[ $TRAVIS_BRANCH =~ (^release) ]]; then ./gradlew clean versionDisplay build bintrayUpload -Pbintray_user=$bintray_user -Pbintray_key=$bintray_key; else ./gradlew clean versionDisplay build; fi
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache"
